name: Terraform Dev
run-name: ${{ github.actor }} is deploying to dev 🚀
environment: dev

on: [push]

jobs:
  tf-pipeline:
    environment: dev
    uses: ./.github/workflows/reuseable.action.yml
    with:
    secrets:
      oidc_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      service_account: ${{ secrets.GOOGLE_IMPERSONATE_SERVICE_ACCOUNT}}



