name: Destroy Infrastructure
run-name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environ:
        description: 'Choose: "dev" or "prod"'
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: '${{ github.event.inputs.environ }}'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: OpenID connect
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd '${{ github.event.inputs.environ }}'
          terraform init

      - name: Destroying ${{ github.events.input.environ }} environment
        run: |
          cd '${{ github.event.inputs.environ }}'
          terraform destroy -auto-approve
