name: Terraform Template

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: "Deployment environment. Valid options: dev or prod"
    secrets:
      service_account:
        required: true
      oidc_provider:
        required: true

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: OpenID connect
        id: auth
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: 'true'
          workload_identity_provider: ${{ secrets.oidc_provider }}
          service_account: ${{ secrets.service_account}}

      - name: 'Setup gcloud SDK'
        uses: google-github-actions/setup-gcloud@v0

      - name: 'login'
        run: gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"

      # - name: Terraform Format
      #   id: fmt
      #   run: terraform fmt -recursive -check

      # - name: Terraform Init
      #   id: init
      #   run: |
      #     cd ${{ inputs.environment }}
      #     terraform init
